markdown: kramdown
plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-avatar
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: pages-themes/hacker@v0.2.0
